name = "worker_yew_spa"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-19"

# `trunk` CLI is required

build = { command = "cargo install -q worker-build && worker-build --release" }

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev -- --features DEBUG" }
# Then, run `trunk serve --watch src/ui --open` in another terminal window
